### ISSUE TITLE
fix for firefox error 400

### ISSUE THREAD

**Issue by Kurairaito** [ratchetphp/RFC6455#14]
Dear,
When trying to open a connection from firefox 44.0.2, it fail everytime because Connection header is not just "Upgrade" as expected. This fix search for the string inside all "Connection header"

0001-fix-error-400-Connection-header-MUST-be-provided-wit.patch.txt
Disabled link, see updated fix on second comment

**Comment by Kurairaito** [comment]
Here is an update of the fix , I didn't noticed that Chrome and edge didn't work anymore due to php sending either FALSE or a number (that could be 0)

[0001-fix-error-400-Connection-header-MUST-be-provided-wit.patch.txt](https://github.com/ratchetphp/RFC6455/files/200751/0001-fix-error-400-Connection-header-MUST-be-provided-wit.patch.txt)

**Comment by mbonneau** [comment]
The header line `Connection: keep-alive, Upgrade\r\n` should create an array of 2 values so that calling [`$request->getHeader('Connection')`](https://github.com/ratchetphp/RFC6455/blob/055b3eca13f314fb910ea55052a9f7d4e516fbc8/src/Handshake/RequestVerifier.php#L26) returns `['keep-alive', 'Upgrade']`. If it is returning `['keep-alive, Upgrade']` then the problem is in the underlying PSR-7 implementation. See http://www.php-fig.org/psr/psr-7/#headers-with-multiple-values

@Kurairaito @pinepain @loconox - Can you provide more information about your environment?

**Comment by loconox** [comment]
Version of psr installed :
psr/http-message                       dev-master 85d6369
guzzlehttp/psr7                        dev-master b1501c9

You can easily reproduce this bug by using the branch ratchet/ratchet 0.4. By the way, on the master branch of this repo, there was a workarround for this "bug", in this file. https://github.com/ratchetphp/Ratchet/blob/master/src/Ratchet/WebSocket/Version/RFC6455/HandshakeVerifier.php

**Comment by mbonneau** [comment]
I am able to reproduce this very simply by using the test echo server.

I was incorrect about this being an issue with the PSR-7 implementation. There is a very complete discussion of how PSR-7 treats headers here: https://mwop.net/blog/2015-07-28-on-psr7-headers.html
